# Generated by Django 5.2.4 on 2025-10-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_letter', models.CharField(max_length=10, verbose_name='korean word')),
                ('meaning_fa', models.CharField(max_length=100, verbose_name='persian word')),
                ('meaning_en', models.CharField(max_length=100, verbose_name='Meaning (English)')),
                ('sound', models.FileField(blank=True, null=True, upload_to='alphabet_sounds/', verbose_name='sound file')),
            ],
        ),
    ]
