# Generated by Django 5.2.4 on 2025-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alphabet',
            name='sound',
        ),
        migrations.AlterField(
            model_name='alphabet',
            name='meaning_en',
            field=models.CharField(max_length=100, verbose_name='english word'),
        ),
    ]
