# Generated by Django 5.2.4 on 2025-10-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_letter', models.CharField(max_length=10, verbose_name='korean word')),
                ('meaning_fa', models.CharField(max_length=100, verbose_name='persian word')),
                ('meaning_en', models.CharField(max_length=100, verbose_name='english word')),
            ],
        ),
    ]
