# Generated by Django 5.2.4 on 2025-10-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alphabetquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphabetquiz',
            name='correct_answer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alphabetquiz',
            name='option1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alphabetquiz',
            name='option2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alphabetquiz',
            name='option3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alphabetquiz',
            name='option4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alphabetquiz',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
